server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
    username: postgres.rzrxgwvawinthekxvnum
    password: Hari@01122004
    driver-class-name: org.postgresql.Driver

    hikari:
      auto-commit: false
      maximum-pool-size: 3      # ⬅️ Reduce pool size to avoid max clients error
      minimum-idle: 1
      idle-timeout: 30000       # 30 seconds
      max-lifetime: 1800000     # 30 minutes
      connection-timeout: 30000 # 30 seconds

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false         # ⬅️ Releases DB connections after transaction ends
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
